### ISSUE TITLE
[Improvement] Show pane with QR text

### ISSUE THREAD

**Issue by zerotosingularity** [msioen/MenuBarCodeReader#1]
At the moment, the text is copied to the clipboard. I thought it might be an improvement to also show a pane with (a list of) scanned text...

**Comment by msioen** [comment]
I'm planning to add in some notification support which will partially resolve this
=> scanned contents appears in notification bar / clicking on it should copy it's contents

**Comment by zerotosingularity** [comment]
hmm, it already gets copied, so a notification would be cool just to
notify... Having to copy it manually would be a step back imho...

Jan Van de Poel

--

M: +32 473 54 70 46
E: jan.vandepoel@summit.be
L: https://www.linkedin.com/in/vandepoel

Zero to singularity - My adventures in deep learning
<https://www.zerotosingularity.com>
Microsoft Most Valuable Professional (MVP) - Visual Studio and Development
Technologies <https://mvp.microsoft.com/en-us/PublicProfile/5002790>

**Comment by msioen** [comment]
I indeed don't want to regress, mainly meant this as an addition
- on successful copy clipboard copy happens and notification is shown
- if you want to check check back later on what was scanned you can check the notifications

I'm possibly thinking about adding a general 'history' but still need to work out how useful this is / where it fits

**Comment by zerotosingularity** [comment]
First time I used it, I expected some kind of pane/window with a list of
"scanned" bar codes... my 2 cents

Jan Van de Poel

--

M: +32 473 54 70 46
E: jan.vandepoel@summit.be
L: https://www.linkedin.com/in/vandepoel

Zero to singularity - My adventures in deep learning
<https://www.zerotosingularity.com>
Microsoft Most Valuable Professional (MVP) - Visual Studio and Development
Technologies <https://mvp.microsoft.com/en-us/PublicProfile/5002790>
